### ISSUE TITLE
change in country name  (from Swaziland to Eswatini)

### ISSUE THREAD

**Issue by silvinabcn** [landportal/data#3]
Hi @dayures ,
This is for when you'll come back to work...
when I run a sparql query (for ex, [this one](https://landportal.org/sparql?default-graph-uri=&query=%23+Get+number+of+observations+by+country+%28including+the+countries+without+any+observation%29%0D%0A%23+Ordered+by+countryURI%0D%0A%0D%0APREFIX+cex%3A+%3Chttp%3A%2F%2Fpurl.org%2Fweso%2Fontology%2Fcomputex%23%3E%0D%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0D%0APREFIX+qb%3A+++%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fcube%23%3E%0D%0A%0D%0ASELECT+DISTINCT+%28STR%28%3Fiso3%29+as+%3Fiso3%29+%3Flabel+%28COUNT%28%3Fobs%29+AS+%3FnObs%29%0D%0AFROM+%3Chttp%3A%2F%2Fdata.landportal.info%3E%0D%0AFROM+%3Chttp%3A%2F%2Fcountries.landportal.info%3E%0D%0AWHERE%7B%0D%0A+++%3FcountryURI+a+%3Chttp%3A%2F%2Fpurl.org%2Fweso%2Flandbook%2Fontology%23Country%3E+%3B%0D%0A+++++++++++++++rdfs%3Alabel+%3Flabel+%3B%0D%0A+++++++++++++++skos%3Anotation+%3Fiso3+.%0D%0A+++OPTIONAL%7B%3Fobs+cex%3Aref-area+%3FcountryURI%7D%0D%0A+++FILTER+isIRI%28%3FcountryURI%29%0D%0A%7D+ORDER+BY+%3FcountryURI&should-sponge=&format=text%2Fhtml&timeout=0&debug=on)), I get the country name Swaziland, but the oficial name is Eswatini (http://www.un.int/eswatini/)
On the website is already updated, please update the name in the Virtuoso. Thanks!

**Comment by dayures** [comment]
great catch! Thanks!

This is already fixed in the <http://countries.landportal.info> graph (using SPARQL Update)
